In [9]:
import numpy as np

In [10]:
# 1. 从Python列表创建
my_list = [1.0, 2.0, 3.0]
arr_a = np.array(my_list)
print(f"A: {arr_a}")

# 2. 创建“占位符”数组（在材料模拟中常用）
# 创建一个 3x3 的全零矩阵（比如，一个晶格矩阵的底子）
arr_zeros = np.zeros((3, 3))
print(f"Zeros:\n {arr_zeros}")

# 创建一个 10x3 的全一矩阵（比如，10个原子的某个属性）
arr_ones = np.ones((10, 3))
# print(f"Ones:\n {arr_ones}")

# 3. 创建“序列”数组（在处理XRD图谱时常用）
# np.arange(start, stop, step) - 不包含stop
arr_range = np.arange(0, 10, 2)
print(f"Range: {arr_range}")

# np.linspace(start, stop, num_points) - 包含stop，科研绘图首选
# 比如模拟一个 2-theta 从10°到80°，共1000个点的XRD图谱
two_theta = np.linspace(10, 80, 1000)
# print(f"2-theta: {two_theta}")

A: [1. 2. 3.]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Range: [0 2 4 6 8]


In [11]:
# 用一个 50个原子 x 3个坐标 的数组举例
# (我们用随机数模拟)
atom_coords = np.random.rand(50, 3)

# 1. .shape (形状) - 最最最重要的属性！
print(f"Shape: {atom_coords.shape}")  # 输出: (50, 3)

# 2. .ndim (维度)
print(f"Ndim: {atom_coords.ndim}")    # 输出: 2 (它是一个二维数组)

# 3. .dtype (数据类型)
print(f"Dtype: {atom_coords.dtype}")  # 输出: float64 (64位浮点数)

Shape: (50, 3)
Ndim: 2
Dtype: float64


In [12]:
# 我们创建一个 4x3 的原子坐标数组
coords = np.array([
    [0.0, 0.0, 0.0],  # 原子 0
    [0.5, 0.5, 0.0],  # 原子 1
    [0.0, 0.5, 0.5],  # 原子 2
    [0.5, 0.0, 0.5]   # 原子 3
])

# 1. 获取单个原子：获取 原子 1 (索引从0开始) 的所有坐标
atom_1 = coords[1, :]
print(f"Atom 1: {atom_1}")  # 输出: [0.5 0.5 0. ]
# 这里的 : 代表“该维度的所有元素”

# 2. 获取单个坐标：获取 原子 3 的 z 坐标
atom_3_z = coords[3, 2]
print(f"Atom 3 (z): {atom_3_z}") # 输出: 0.5

# 3. 获取“所有”原子的 x 坐标
all_x = coords[:, 0]
print(f"All x-coords: {all_x}") # 输出: [0.  0.5 0.  0.5]

# 4. 获取“前两个”原子的 x, y 坐标
# 0:2 代表“从索引0开始，到索引2结束（不含2）”
first_two_xy = coords[0:2, 0:2]
print(f"First two xy:\n {first_two_xy}")

Atom 1: [0.5 0.5 0. ]
Atom 3 (z): 0.5
All x-coords: [0.  0.5 0.  0.5]
First two xy:
 [[0.  0. ]
 [0.5 0.5]]


In [14]:
# 假设一个简单的立方晶格
lattice = np.array([
    [3.8, 0.0, 0.0],
    [0.0, 3.8, 0.0],
    [0.0, 0.0, 3.8]
])

# 两个原子的分数坐标
frac_coords = np.array([
    [0.0, 0.0, 0.0],  # (0, 0, 0)
    [0.5, 0.5, 0.5]   # (0.5, 0.5, 0.5)
])

# 使用 np.dot() 或 @ 运算符进行矩阵乘法
cart_coords = np.dot(frac_coords, lattice)
# 或者: cart_coords = frac_coords @ lattice

print(f"Lattice (shape {lattice.shape}):\n {lattice}")
print(f"Frac Coords (shape {frac_coords.shape}):\n {frac_coords}")
print(f"Cart Coords (shape {cart_coords.shape}):\n {cart_coords}")

Lattice (shape (3, 3)):
 [[3.8 0.  0. ]
 [0.  3.8 0. ]
 [0.  0.  3.8]]
Frac Coords (shape (2, 3)):
 [[0.  0.  0. ]
 [0.5 0.5 0.5]]
Cart Coords (shape (2, 3)):
 [[0.  0.  0. ]
 [1.9 1.9 1.9]]
